development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  pool: 5
  username: hanh
  password: 1234abcd

test: &test
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  pool: 5
  username: hanh
  password: 1234abcd

production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
  pool: 5
  username: hanh
  password: 1234abcd
cucumber:
  <<: *test