development:
  adapter: postgresql
  encoding: utf8
  database: sample_app_development
  pool: 5
  username: hanhleemin
  password: 1234abcd

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: sample_app_test
  pool: 5
  username: hanhleemin
  password: 1234abcd

production:
  adapter: postgresql
  encoding: utf8
  database: sample_app_production
  pool: 5
  username: hanhleemin
  password: 1234abcd